version: '3.7'
services:
  zipkin:
    image: openzipkin/zipkin-slim:2.19
    ports:
      - '127.0.0.1:9411:9411'

  recipe-api:
    build:
      context: ./src/recipe-api
      dockerfile: ./src/recipe-api/Dockerfile-zipkin
    ports:
      - '127.0.0.1:4000:4000'
    environment:
      ZIPKIN: zipkin:9411
    depends_on:
      - zipkin

  web-api:
    build:
      context: ./src/web-api
      dockerfile: Dockerfile-zipkin
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      TARGET: recipe-api:4000
      ZIPKIN: zipkin:9411
    depends_on:
      - zipkin
      - recipe-api
