FROM node:14.8.0-alpine3.12
WORKDIR /srv

COPY ./package*.json ./
COPY ./tsconfig.* ./
COPY ./src/recipe-api/producer-http-zipkin.ts ./src/producer.ts

RUN npm i --ignore-scripts \
  && npm run compile

COPY . .

CMD [ "node", "dist/producer.js" ]
