FROM node:14.8.0-alpine3.12
WORKDIR /srv

COPY ./package*.json ./
COPY ./tsconfig.* ./
COPY ./src/web-api/consumer-http-zipkin.ts ./src/consumer.ts

RUN npm i --ignore-scripts \
  && npm run compile

COPY . .

CMD [ "node", "dist/consumer.js" ]
