# https://kubernetes.io/docs/concepts/services-networking/service/
# kubectl apply -f minikube/recipe-service.yml
apiVersion: v1

kind: Service

metadata:
  name: recipe-api-service

spec:
  type: NodePort

  selector:
    app: recipe-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337
